### PR TITLE
upgrade pkg nat-server to 2.7.2(release-2.4)

### PR DESCRIPTION
**Pull request by marcolan018**
Signed-off-by: marcolan018 <llan@redhat.com>
https://github.com/stolostron/backlog/issues/20183

* [ ] I added CHANGELOG entry for this change.
* [ ] Change is not relevant to the end user.

### CODE REVIEW

**Comment by pshickeydev** [comment]
Please wait for 2.4.5 to be open to merge this PR.

**Comment by clyang82** [comment]
There are 2 files not complaint with the latest format for 1.17 after running `make format` so you need to commit them firstly and then upgrade the version of `faillint` for 1.17 go

**Pull request merged**
