### PR TITLE
Upgrade v0.29.0

### PR DESCRIPTION
**Pull request by ngraham20**

### CODE REVIEW

**Comment by ngraham20** [comment]
Thanos image worked as expected in testing, and the sonar-pre-submit can be debugged at a later point. Overriding for now.

**Comment by dislbenn** [comment]
/override ci/prow/sonar-pre-submit

Overriding the `sonar-pre-submit` job to unblock this PR. The unit test and e2e test cases are passing; therefore, we will debug the `sonar` job within a separate PR.

**Pull request merged**
