### PR TITLE
Update to Thanos v0.34.1

### PR DESCRIPTION
**Pull request by subbarao-meduri**
[ACM-10836](https://issues.redhat.com/browse/ACM-10836)

Sync stolostron fork to be at 0.34.1 upstream level.

### CODE REVIEW

**Comment by subbarao-meduri** [comment]
Upgraded go version to 1.21 for CI pipeline via [PR 51890](https://github.com/openshift/release/pull/51890)

**Review by saswatamcode — APPROVED** [review]
/lgtm

**Pull request merged**
